name: My github flow

on: [push, fork]

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List and Read file
        run: |
          echo "My test github action"
          ls -lrt
          cat README.md

      - name: Generate ascii content
        run: cowsay -f dragon "Run for cover" >> dragon.txt

    #   - name: list files
    #     run: ls

    #   - name: Read file
    #     run: cat README.md
