name: My github flow

on: [push, fork]

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome msg
        run: echo "My test github action"

      - name: list files
        run: ls

      - name: Read file
        run: cat README.md
